definitions:
  models.Metrics:
    properties:
      alltime_income:
        type: integer
      alltime_out:
        type: integer
      current_users:
        type: integer
      income_sub_out:
        type: integer
    type: object
  models.MetricsSet:
    properties:
      alltime_income:
        type: integer
      alltime_out:
        type: integer
      current_users:
        type: integer
    type: object
  models.Rate:
    properties:
      id:
        type: integer
      min_lock_days:
        type: integer
      profit:
        type: integer
      properties: {}
      title:
        type: string
    type: object
  models.RateCreate:
    properties:
      min_lock_days:
        type: integer
      profit:
        type: integer
      properties: {}
      title:
        type: string
    type: object
  models.Review:
    properties:
      id:
        type: integer
      properties: {}
      text:
        type: string
      tittle:
        type: string
    type: object
  models.ReviewCreate:
    properties:
      properties: {}
      text:
        type: string
      tittle:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/rate:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: Reviews per page
        in: query
        name: per_page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Array
          schema:
            items:
              $ref: '#/definitions/models.Rate'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - admin
    post:
      consumes:
      - application/json
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.RateCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - admin
    put:
      consumes:
      - application/json
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.Rate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - admin
  /admin/static/metrics:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Successfully
          schema:
            $ref: '#/definitions/models.Metrics'
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - admin
    post:
      consumes:
      - application/json
      parameters:
      - description: Metrics updated
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.MetricsSet'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated metrics
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - admin
  /admin/static/review:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Review ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - admin
    get:
      consumes:
      - application/json
      parameters:
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: Reviews per page
        in: query
        name: per_page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Array of reviews
          schema:
            items:
              $ref: '#/definitions/models.Review'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - admin
    post:
      consumes:
      - application/json
      parameters:
      - description: Review create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.ReviewCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created review
          schema:
            type: integer
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - admin
    put:
      consumes:
      - application/json
      parameters:
      - description: Review
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.Review'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - admin
swagger: "2.0"
